#!/bin/sh
set -e

CONF_FILE="/app/ninja-server.conf"

# Auto-detect the container's own IP address unless SERVER_IP is explicitly set.
# This matters because docker's port-forwarding (-p 8053:53/udp) performs DNAT to the
# container's internal address, so the "ip dst" the scapy sniff filter must match is
# the container's own IP, not the host's public IP.
if [ -z "${SERVER_IP}" ]; then
    SERVER_IP=$(hostname -i | awk '{print $1}')
fi

SERVER_DOMAIN=${SERVER_DOMAIN:-ninja.example.com}

if [ ! -f "${CONF_FILE}" ]; then
    cat > "${CONF_FILE}" <<EOF
---
ServerIP: ${SERVER_IP}
ServerDomain: ${SERVER_DOMAIN}
EOF
fi

echo "Using config:"
cat "${CONF_FILE}"

# Since scapy doesn't actually bind to UDP port 53, but only sniffs incoming traffic,
# the kernel doesn't know that the queries received on port 53 are being "answered",
# so it would normally reply with ICMP port-unreachable messages. Drop those so the
# real DNS response generated by dns-ninja-server.py isn't followed/confused by an
# ICMP error for the same query. This requires the NET_ADMIN capability (already
# declared in docker-compose.yml).
if command -v iptables >/dev/null 2>&1; then
    iptables -I OUTPUT -p icmp --icmp-type destination-unreachable -j DROP \
        || echo "Warning: could not install iptables rule to drop ICMP destination-unreachable packets (missing NET_ADMIN capability?)" >&2
fi

exec python /app/dns-ninja-server.py

